### ISSUE TITLE
backspace-delete and arrow-keys should be limited to the writable ranges

### ISSUE THREAD

**Issue by milahu** [andrebnassis/codemirror-readonly-ranges#3]
im migrating [cmjs-shell](https://github.com/sdllc/cmjs-shell) ([demo](http://sdllc.github.io/cmjs-shell/demo/)) to codemirror 6 in [codemirror-shell](https://github.com/milahu/codemirror-shell)

to make the terminal history readonly im using

```js
let PS1 = "> "

// FIXME backspace-delete and arrow-keys should be limited to the writable range
function getReadOnlyRanges(targetState) {
  // workaround so i can add content with view.dispatch()
  if (targetState.doc.lines <= 1) {
    return []
  }
  return [
    {
      from: 0,
      to: targetState.doc.line(targetState.doc.lines).from + PS1.length
    },
  ]
}

let view = new EditorView({
  extensions: [
    readOnlyRangesExtension(getReadOnlyRanges),
  ],
  doc: "",
  parent: document.body,
})
```

so only the last line (minus $PS1) is writable

problem is, backspace-delete and arrow-keys can still move the cursor into the readonly range

**Comment by andrebnassis** [comment]
This could be configurable and a new feature, but I don't think that it is a bug. Feel free to create a PR with some suggestions for this problem you are facing, I'll evaluate and if everything is good I'll approve it.
